# Generated by Django 4.0 on 2021-12-13 20:03

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guest_can_play',
        ),
        migrations.AddField(
            model_name='room',
            name='hiddenNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=pages.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
