# Generated by Django 4.0 on 2021-12-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_room_guest_can_play_room_hiddennum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guest_can_play',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='hiddenNum',
            field=models.IntegerField(default=False),
        ),
    ]
