# Generated by Django 4.0 on 2021-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_room_guest_can_play_alter_room_hiddennum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hiddenNum',
            field=models.IntegerField(default=1),
        ),
    ]
