# Generated by Django 4.0 on 2021-12-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_hiddennum_room_hidden_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='is_host',
        ),
    ]
