# Generated by Django 4.0 on 2021-12-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_room_ana_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ana_word',
        ),
    ]
