# Generated by Django 4.0 on 2021-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_room_ana_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ana_word',
            field=models.CharField(default='', max_length=10),
        ),
    ]
