# Generated by Django 4.0 on 2021-12-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_room_ana_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_words',
            field=models.CharField(default='gdgd', max_length=200),
            preserve_default=False,
        ),
    ]
