# Generated by Django 4.0 on 2021-12-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_room_all_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
