# Generated by Django 4.0 on 2021-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_room_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
