# Generated by Django 4.0 on 2021-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_room_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='all_words',
            field=models.CharField(max_length=500),
        ),
    ]
