# Generated by Django 4.0 on 2021-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_room_all_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='all_words',
            field=models.CharField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='room',
            name='ana_word',
            field=models.CharField(default='starter', max_length=10),
        ),
    ]
