# Generated by Django 4.0 on 2021-12-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_room_all_words_alter_room_ana_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='final_words',
            field=models.CharField(default=' ', max_length=500000),
        ),
    ]
